enterFirstName = "id:firstname"
enterLastName = "id:lastname"
signinCheckBox = "id:is_subscribed"
enterEmail="id:email_address"
enterPassword="id:password"
enterConfirmPassword="id:password-confirmation"
btnSubmit="class:submit"
btnSignOut="class:customer-name"
